### ISSUE TITLE
Ireadit vs watchcycle Plugin

### ISSUE THREAD

**Issue by Marcao8** [gkrid/dokuwiki-plugin-ireadit#12]
Hello Folks,
first of all, Ireadit is a great plugin for quality managment systems, where certain users have to sign new processes in their namespace. So thank you for making it.
But it seems to have a problem with the Browser edge, because when I add the ~~ireadit~~ command there, the hole text crashes and all the raw code is displayed on the wikipage. In Firefox also, no button is displayed, just text link, witch registers the user has read it. 
see: https://i.imgur.com/QAMIyic.jpg?1

The second problem is, when i add the plugin WATCHCYCLE in addition, the page gets corrupted. here is the sourcecode:

```
<h1 class="page-header">Process</h1>

~~WATCHCYCLE:superuser:28~~

<div class="level1">
<p>some Text</p>

<pre class="code">
a box



</pre>

<p>&nbsp;</p>

<p>Now something has changed.</p>

<hr />~~IREADIT~~</div>
```

after saveing the changes, the page is nearly empty. Just the maintainance box is shown
see: https://i.imgur.com/lvnCqkk.jpg

It would be great, if someone could fix the button display and also the compatibility with the page update managment plugin. 
Thanks for every help.
Marcao

**Comment by solewniczak** [comment]
Let's start with the first issue. Can you send me the source code of the wiki page that crashes on Edge (or better the minimal part that causes the crash)? What version of PHP and dokuwiki do you using? Can you tell me what template do you have and which dokuwiki plugins you have installed?

**Comment by Marcao8** [comment]
For testing pourpose the Dokuwiki-stickversion is used at the moment. The first issue in edge **resolved** today, i don't know what could have caused it, because no significant changes were made.

Also, after adding both commands **to the top** of the pagefile, both plugins can be used as well. The error seems to occour, if the `~~IREADIT~~` command is written after the main text.
 
```
<p>~~IREADIT~~</p>

<p>~~WATCHCYCLE:marelsi:28~~</p>

<h1 class="page-header">Process Name</h1>

<div class="level1">
<p>Here is some text for process description.</p>
</div>
```

Thank you anyways. One last question: is it possible to use the "I've read it." link in a button, so that it is more outstandig from the text?

**Comment by solewniczak** [comment]
No problem. I'll add it in next release.
