### ISSUE TITLE
ireadit breaks Dokuwiki (blank page)

### ISSUE THREAD

**Issue by retrofreak83** [gkrid/dokuwiki-plugin-ireadit#23]
I just upgraded to Dokuwiki 2018-04-22c and also to the newest ireadit version. sqlite plugin is installed. As soon as I install the new ireadit version, I only get a blank page and in the Apache error logs there is:
`Call to a member function getName() on null in [REDACTED]wiki/lib/plugins/ireadit/helper/db.php on line 44`

A shot in the dark: May it be that the current ireadit version does not support PHP 5?

**Comment by solewniczak** [comment]
It seems like you don't have pdo_sqlite extension installed. Pleas check it.

**Comment by retrofreak83** [comment]
You are right, now it works. Thanks!
