### ISSUE TITLE
Create a list of pages that user has not yet read

### ISSUE THREAD

**Issue by solewniczak** [gkrid/dokuwiki-plugin-ireadit#7]
Hi, I like the plugin. That's what I was looking for! Now I need the option to create a list of pages that a user has not yet read, but that are marked with ~~IREADIT~~. Is that possible? Thanks! +1

**Comment by jamesinjapan** [comment]
I'm interested in a feature like this too.

**Comment by akanezumi** [comment]
This sounds _very_ useful. I would also appreciate this

**Comment by Marcao8** [comment]
Yes this would be a great feature. I guess it could be displayed as a notification, similar to the cookie banner.

**Comment by solewniczak** [comment]
Implemented in **2019-09-02**
